# Site
repository: hjhbboy/hjhbboy.github.io
# favicon: images/favicon.ico

# Personal info
name: 황지환
title: 공장 자동화 엔지니어
email: zhwan.hwang@gmail.com
# website: http://zhwan.info/

# Social links
# twitter_username: 
# github_username:  
# dribbble_username: jekyll
# facebook_username: 
# flickr_username: jekyll
# linkedin_username: 
# pinterest_username: jekyll
# youtube_username: 

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  LCD, 반도체 분야의 공장 자동화 제품 개발 및 적용을 해 왔습니다. 총 경력은 19년차 이고, Project Leader의 역할은 2013년도 부터 진행해 왔습니다.<br/><br/>
  점진적으로 성장가능한 시스템을 구축해야 한다는 생각에 테스트 시스템 구축을 당연하게 생각하고, 코드 품질 및 개발 생산성 향상을 위한 환경을 구성하였습니다.
  또한, 올바른 Object Oriented Programming과 Domain Driven Design을 적용하고자 노력하고 있습니다.<br/><br/>
  현재는 개발팀장으로 제품 개발 설계/구현, 팀원과 팀의 성장 등을 주요 업무로 하고 있습니다.<br/><br/>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
